### ISSUE TITLE
sendxyh_new.py如果当天数据没有会报这样的错误

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/chstockbot#138]
今天完蛋了，什么都不知道，快去通知管理员，bot已经废物了，出的问题是:
<class 'ZeroDivisionError'>:
division by zero
Traceback (most recent call last):
  File "/Users/hd/work/hdcola/chstockbot/sendxyh_new.py", line 61, in <module>
    data = index.compare_avg(ma=50,end_date=target_date)
  File "/Users/hd/work/hdcola/chstockbot/stockutil/index.py", line 67, in compare_avg
    return {'up_num':len(up), 'down_num':len(down),'rate':len(up)/(len(up)+len(down)), 'today_volume': today_volume, 'yesterday_volume':yesterday_volume, 'percentage':(today_volume - yesterday_volume)/yesterday_volume,'err_msg': err_msg}
ZeroDivisionError: division by zero

**Comment by stephenzhu01** [comment]
如果是因为当天没有数据的话，我在load data的时候根据拿到的数据信息，对start和end做了reset。所以就不会报这个错误。然后输出的 spx和ndx msg里面加上了交易量对应的日期信息。
