### ISSUE TITLE
把util中的两个函数合并

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/chstockbot#163]
# TODO 这两个函数是一样的，需要做一个选择
def get_target_date(start=datetime.date.today(),end=datetime.date.today(),freq="W-WED"): #获得指定日期中的周三 可以扩展成任何天数
    """
    freq="W-DAY" i.e, W-MON/W-TUE/W-WED/W-THU/W-FRI/W-SAT/W-SUN
    """
    date_list = pd.date_range(start=start, end=end, freq=freq).tolist()

    date_dict = {}
    date_dict["xmm"] =date_list
    date_dict["dmm"] = []

    for date in date_list:
        if is_second_wednesday(date):
            date_dict["dmm"].append(date)
    return date_dict

# TODO 区别在于week_num，另外dtae_list是否需要改成list :)
def get_date_list(start_date=None,end_date=None,freq='W-WED', week_num = 2):
    """
    freq="W-DAY" i.e, W-MON/W-TUE/W-WED/W-THU/W-FRI/W-SAT/W-SUN
    """
    date_list = pd.date_range(start=start_date, end=end_date, freq=freq).tolist()
    date_lists = {}
    date_lists['xmm'] = date_list
    date_lists['dmm'] = []
    for date in date_list:
        if get_week_num(date.year, date.month, date.day) == week_num:
            date_lists['dmm'].append(date)
    return date_lists

记得重构后看看test是不是都运行正常啊

**Comment by stephenzhu01** [comment]
week num这个函数目前其实是有点问题的。仅仅是某个月第二周，并不是含有周三的第二周。
是否需要继续使用这个函数是在于咱们这个第二周会不会变为第一周、第三周（譬如为了做对比）。 不需要的话就可以直接用get target price

**Comment by hdcola** [comment]
我觉得可以支持第一周的周几这样，可以量化的说明定投策略的方式

**Comment by stephenzhu01** [comment]
> 我觉得可以支持第一周的周几这样，可以量化的说明定投策略的方式

我昨天给这个函数做了点调整，逻辑上符合目前 “本月第二个含有周三的 周”。 并且如果需要和其他交易策略做对比，也可以很方便调整。
