### ISSUE TITLE
return f"cannot found df, skip\n"会发给用户

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/chstockbot#35]

**Comment by hdcola** [comment]
重现方法就是
['aaabbb',10,20]

**Comment by lben1216** [comment]
部分测试的实例：
1. 当所有的数据源都是无效的时候， 程序应该报错
2. 当第一个数据源有效时，程序应该继续运行
3. 当有数据源无效，程序应该持续尝试直到成功读取数据源的数据； 如果没有有效的数据源，程序报错
4. 当数据源和股票代码都无效的时候，程序应该向admin报告数据源无效，不应该向用户发送信息
5. 当股票代码无效的时候，程序应该继续运行并在最后向用户发出信息（在交易日时）
6. 当不在交易日时，程序不计算均价并向admin报告该信息

**Comment by hdcola** [comment]
fix by #52
